name: Build and Deploy Micronaut Project with Gradle DockerBuild Task

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/wrapper-validation@v3

      - name: Build Micronaut Project and Docker Image
        run: |
          ./gradlew build dockerBuild

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag spoonfull:latest joshuabaker97/spoonfull:${{ github.run_number }}
          docker tag spoonfull:latest joshuabaker97/spoonfull:latest
  
          # Push the tagged images to Docker Hub
          docker push joshuabaker97/spoonfull:${{ github.run_number }}
          docker push joshuabaker97/spoonfull:latest
